# Generated by Django 3.2.5 on 2021-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_itemscart'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
